config/routes.rb
Poemarkets::Application.routes.draw do
  root 'search#index'

  get '/search' => 'search#index'
  get '/search/:slug' => 'search#index'
  get '/results/:slug' => 'search#results'
  get '/results' => 'search#results'
  get '/items/verify/:id' => 'items#verify', defaults: { format: 'json' }
  get '/items/similar_names' => 'items#similar_names'
  get '/items/base_types' => 'items#base_types', defaults: { format: 'json' }
  get '/seller/:uuid' => 'sellers#index'
  put '/seller/:uuid/status' => 'sellers#status'
  put '/seller/:uuid/updateign' => 'sellers#updateign'
  put '/seller/:uuid/offline' => 'sellers#offline'
  
  get '/buyout-tags' => 'static#buyout_tags'
  
  namespace :admin do
    get '/' => 'admin#index'
  end
  

  namespace :admin do
    resources :leagues
    resources :forums
    resources :currency_ratios
  end

end

app/models/league.rb
class League < ActiveRecord::Base
  
  has_many :items, dependent: :destroy
  has_many :forums, dependent: :destroy
  has_many :currency_ratios, dependent: :destroy
  belongs_to :region
  
  def create_view
    League.connection.execute("
    CREATE VIEW #{self.view_name} AS SELECT items.* FROM items INNER JOIN leagues ON items.league_id = leagues.id AND leagues.id = #{self.id};
    ")
  end
  
  def drop_view
    begin
      League.connection.execute("
    DROP VIEW #{self.view_name};
    ")
    rescue
      Rails.logger.warn "Failed to delete view #{self.view_name}"
    end
  end
  
  def populate_ratios
    standard = League.find_by_name('Standard')
    ratios = CurrencyRatio.where(league: standard)
    
    ratios.each do |ratio|
      CurrencyRatio.create(league: self, currency: ratio.currency, chaos_ratio: ratio.chaos_ratio)
    end
  end
  
  def view_name
    (self.region.name + ' ' + self.name + ' items').parameterize.underscore
  end
end

app/controllers/admin/leagues_controller.rb
class Admin::LeaguesController < Admin::AdminController
  
  def index
    @leagues = League.all
  end
  
  def destroy
    @league = League.find(params[:id])
    @league.drop_view
    @league.destroy
    
    flash[:notice] = "League deleted successfully"
    
    respond_to do |format|
      format.html { redirect_to admin_leagues_path }
    end
  end
  
  def new
    @league = League.new
  end
  
  def create
    @league = League.new(league_params)
    
    if @league.save
      
      @league.create_view
      @league.populate_ratios
      
      flash[:notice] = "League added successfully"

      respond_to do |format|
        format.html { redirect_to admin_leagues_path }
      end
    else
      flash.now[:error] = "Could not save league"
      render action: "new"
    end
  end
  
  private
  
  def league_params
    params.require(:league).permit(:name, :region_id)
  end
  
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/admin/leagues/index.html.erb
<%= link_to "Add New League", new_admin_league_path %>
<table class="table">
<thead>
  <tr>
    <th>League</th>
    <th>Edit<th>
    <th>Delete</th>
  </tr>
</thead>
<tbody>
  <% @leagues.each do |league| %>
  <tr>
    <th><%= league.name %></th>
    <td>E</td>
    <td><%= link_to "Delete", admin_league_path(league), method: :delete %></td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/admin/leagues/new.html.erb
<h1>Create New League</h1>
<%= form_for @league, url: { action: :create }, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :name, "League Name" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :region, "Region" %>
    </div>
    <div class="col-sm-10">
      <%= f.select :region_id, options_from_collection_for_select(Region.all, :id, :name) %>
    </div>
  </div>
  <%= f.submit "Create", class: 'btn btn-success' %>
<% end %>