config/routes.rb
Poemarkets::Application.routes.draw do
  root 'search#index'

  get '/search' => 'search#index'
  get '/search/:slug' => 'search#index'
  get '/results/:slug' => 'search#results'
  get '/results' => 'search#results'
  get '/items/verify/:id' => 'items#verify', defaults: { format: 'json' }
  get '/items/similar_names' => 'items#similar_names'
  get '/items/base_types' => 'items#base_types', defaults: { format: 'json' }
  get '/seller/:uuid' => 'sellers#index'
  put '/seller/:uuid/status' => 'sellers#status'
  put '/seller/:uuid/updateign' => 'sellers#updateign'
  put '/seller/:uuid/offline' => 'sellers#offline'
  
  get '/buyout-tags' => 'static#buyout_tags'
  
  namespace :admin do
    get '/' => 'admin#index'
  end
  

  namespace :admin do
    resources :leagues
    resources :forums
    resources :currency_ratios
  end

end

app/models/currency_ratio.rb
class CurrencyRatio < ActiveRecord::Base
  
  belongs_to :league
  belongs_to :currency
end

app/controllers/admin/currency_ratios_controller.rb
class Admin::CurrencyRatiosController < Admin::AdminController
  
  def index
    @ratios = CurrencyRatio.all
  end
  
  def destroy
    @ratio = CurrencyRatio.find(params[:id])
    @ratio.destroy
    
    flash[:notice] = "Ratio deleted successfully"
    
    respond_to do |format|
      format.html { redirect_to admin_currency_ratios_path }
    end
  end
  
  def new
    @ratio = CurrencyRatio.new
  end
  
  def create
    @ratio = CurrencyRatio.new(ratio_params)
    
    if @ratio.save
      
      flash[:notice] = "Ratio added successfully"

      respond_to do |format|
        format.html { redirect_to admin_currency_ratios_path }
      end
    else
      flash.now[:error] = "Could not save ratio"
      render action: "new"
    end
  end
  
  private
  
  def ratios_params
    params.require(:ratio).permit(:currency_id, :league_id, :chaos_ratio)
  end
  
end

app/helpers/currency_ratios_helper.rb
module CurrencyRatiosHelper
end

app/views/admin/currency_ratios/index.html.erb
<table class="table">
<thead>
  <tr>
    <th>League</th>
    <th>Currency</td>
    <td>Chaos Ratio</td>
    <th>Edit<th>
    <th>Delete</th>
  </tr>
</thead>
<tbody>
  <% @ratios.each do |ratio| %>
  <tr>
    <th><%= ratio.league.name %></th>
    <td><%= ratio.currency.name %></td>
    <td><%= ratio.chaos_ratio%>
    <td>Edit</td>
    <td><%= link_to "Delete", admin_currency_ratio_path(ratio), method: :delete %></td>
  </tr>
  <% end %>
</tbody>
</table>