config/routes.rb
Poemarkets::Application.routes.draw do
  root 'search#index'

  get '/search' => 'search#index'
  get '/search/:slug' => 'search#index'
  get '/results/:slug' => 'search#results'
  get '/results' => 'search#results'
  get '/items/verify/:id' => 'items#verify', defaults: { format: 'json' }
  get '/items/similar_names' => 'items#similar_names'
  get '/items/base_types' => 'items#base_types', defaults: { format: 'json' }
  get '/seller/:uuid' => 'sellers#index'
  put '/seller/:uuid/status' => 'sellers#status'
  put '/seller/:uuid/updateign' => 'sellers#updateign'
  put '/seller/:uuid/offline' => 'sellers#offline'
  
  get '/buyout-tags' => 'static#buyout_tags'
  
  namespace :admin do
    get '/' => 'admin#index'
  end
  

  namespace :admin do
    resources :leagues
    resources :forums
    resources :currency_ratios
  end

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  belongs_to :league
end

app/controllers/admin/forums_controller.rb
class Admin::ForumsController < Admin::AdminController
  
  def index
    @forums = Forum.all
  end
  
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy
    
    flash[:notice] = "Forum deleted successfully"
    
    respond_to do |format|
      format.html { redirect_to admin_forums_path }
    end
  end
  
  def new
    @forum = Forum.new
  end
  
  def create
    @forum = Forum.new(forum_params)
    
    if @forum.save
      
      flash[:notice] = "Forum added successfully"

      respond_to do |format|
        format.html { redirect_to admin_forums_path }
      end
    else
      flash.now[:error] = "Could not save forum"
      render action: "new"
    end
  end
  
  private
  
  def forum_params
    params.require(:forum).permit(:url, :league_id)
  end
  
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/admin/forums/index.html.erb
<%= link_to "Add New Forum", new_admin_forum_path %>
<table class="table">
<thead>
  <tr>
    <th>Region</th>
    <th>League</th>
    <th>Forum</th>
    <th>Edit<th>
    <th>Delete</th>
  </tr>
</thead>
<tbody>
  <% @forums.each do |forum| %>
  <tr>
    <td><%= forum.league.region.name %></td>
    <td><%= forum.league.name %></td>
    <td><%= forum.url %></td>
    <td>E</td>
    <td><%= link_to "Delete", admin_forum_path(forum), method: :delete %></td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/admin/forums/new.html.erb
<h1>Create New Forum</h1>
<%= form_for @forum, url: { action: :create }, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :name, "League" %>
    </div>
    <div class="col-sm-10">
      <%= f.select :league_id, option_groups_from_collection_for_select(Region.all, :leagues, :name, :id, :name) %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :url, "Url" %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :url %>
    </div>
  </div>
  <%= f.submit "Create", class: 'btn btn-success' %>
<% end %>